// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSfj-snBhzrTvfgBMa295lpHiI1QdQZQ',
    appId: '1:873318761374:web:34f494cfd62b50179a0c8f',
    messagingSenderId: '873318761374',
    projectId: 'mosque-c27a5',
    authDomain: 'mosque-c27a5.firebaseapp.com',
    storageBucket: 'mosque-c27a5.appspot.com',
    measurementId: 'G-C9GWKWM5GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHBxuUFMzc3R96vaWuYswnv2zQLBZBPv8',
    appId: '1:873318761374:android:b45c65c6759cbf079a0c8f',
    messagingSenderId: '873318761374',
    projectId: 'mosque-c27a5',
    storageBucket: 'mosque-c27a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7RcZTIPygxrcrf8GYy5WbdGBfea7HCEk',
    appId: '1:873318761374:ios:804797aa1f8d8c549a0c8f',
    messagingSenderId: '873318761374',
    projectId: 'mosque-c27a5',
    storageBucket: 'mosque-c27a5.appspot.com',
    iosBundleId: 'com.example.mosque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7RcZTIPygxrcrf8GYy5WbdGBfea7HCEk',
    appId: '1:873318761374:ios:acfa9a52a6d73bb59a0c8f',
    messagingSenderId: '873318761374',
    projectId: 'mosque-c27a5',
    storageBucket: 'mosque-c27a5.appspot.com',
    iosBundleId: 'com.example.mosque.RunnerTests',
  );
}
